- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
Runs only a single Rubocop command, and filters out the appropriate files from the report before generating the table of violations to include in Danger's PR comment.
This means that `Exclude` settings for `AllCops` in `.rubocop.yml` will be respected.
Resolves #6 
Let me know how this looks to you, @ashfurrow :) I've tested it in a private repo of ours and it's working nicely.
> Run rubocop just once (respecting excludes specified in .rubocop.yml)

- Gemfile.lock
- spec/danger_plugin_spec.rb
More recent versions of Danger model markdown as a model object instead
of as a String. This caused test breakage against new versions of
Danger.
This change addresses the issue by:
* Updating tests to access the 'message' attribute of Markdown objects
> Update specs for Danger markdown

- lib/danger_plugin.rb
Added `offending_file` public method to be possible use `github.api` (src.: http://danger.systems/reference.html) in dangerfile (to add comments via Github API).
#needMoreTests
> Add offending_file public method

- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
- spec/fixtures/shellescape/ruby_file with spaces.rb
- spec/fixtures/shellescape/ruby_file'with_quotes.rb
- spec/fixtures/shellescape/ruby_file_with_parens_(abc).rb
Files with spaces, quotes, parens and others that need shellescaping
were breaking the rubocop command, because they were not escaped.
[`Shellwords`][1] comes with the ruby stdlib and does exactly what is needed.
It will escape every element of the `files_to_lint` array and then join
it together.
Fixes #12 
✨ 
[1]: https://ruby-doc.org/stdlib-2.3.0/libdoc/shellwords/rdoc/Shellwords.html
> Shellescape rubocop file list

- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
Hello, first of all, thanks for this plugin!
I'd like Rubocop to lint all ruby files changed in PR except those excluded by `.rubocop.yml`.
I could limit set of files to lint in Dangerfile, but that effectively means duplicating the contents of `.rubocop.yml`, which I'd like to avoid.
Highlights:
* Supports configuration hash as `lint` argument
* Simplifies plugin logic to avoid multiple filesystem hits and implicit parameter passing
* Introduces `force_exclusion` flag to pass `--force-exclusion` to Rubocop.
> Support `--force-exclusion` flag to make Rubocop respect exclusions specified in its config file

- README.md
Hi,
I've made a whole issue of the problem (https://github.com/ashfurrow/danger-rubocop/issues/19), and found myself a little silly for not noticing it was already solved... so I thought I'd help the next silly person get what the forced_exclusion option is for at first sight ^^
Cheers, and thanks for this super plugin ^^d
> Explains the forced_exclusion option a little more

- README.md
- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
This P-R adds support for danger's inline commenting, [introduced about a year ago](https://github.com/danger/danger/pull/412), by passing `file` and `line` arguments to `warn`.
The added test still fails. It'll pass once https://github.com/danger/danger/pull/894 is merged.
> Add inline_comment option to rubocop.lint

- README.md
- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
This is kind of rudimentary solution to #18 
Adding  a config `report_danger` boolean flag, to send as Danger messages the Rubocop errors.
TODO: Write some tests
> Add direct danger option

- README.md
- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
I have been running `rubocop` in our application on CircleCI to lint our Ruby code,  so if any offense is detected in a pull request, CircleCI will report a failure and mark CI status as failed.
I want to replace `rubocop` with `danger` with danger-rubocop to use its great inline comment feature but there is a problem that it won't block CI if any offense is detected.
Following the problem, I added `:fail_on_inline_comment` option so that we can let `danger` report failures on inline comments instead of warnings. 
This is an example result with `{ fail_on_inline_comment: true, inline_comment: true }`:
> Add :fail_on_inline_comment option

- README.md
- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
Hi, and thanks for the good work :clap:
Using the plugin, my team ended up being frustrated having Rubocop messages for contribution they didn't make.
Here is my way of solving this issue:
1. check out offenses as usual
2. check out which lines of code are new using `git.diff_for_file.patch`
3. removing offenses which are not within these lines of code
There is an issue left, that I documented: when you are dealing with block length issues such as `Metric/MethodLength`, they will be excluded if you are in an already created method. This is definitely fixable but I won't have the time here, and I think it is not mandatory yet, as long as it is documented.
Tell me what you think,
I'd love to see that merged asap, in the mean time I'll use a little hack to make it work in my team's (@klaxit) …
> add `only_report_new_offenses` option

- README.md
When submitting the inline comment, if the referenced line is not present in the patch, Danger aggregates the message into a main comment (see at the end of Github reference here: https://danger.systems/reference.html ). which is usually not a desired outcome.
Fortunately the problem can be solved without adding any complexity to `danger-rubocop` - by using Danger DSL instead.
It feels like a pretty popular use case, so I thought it may be worth adding it to the README
Closes #28
> Document the instructions for having Danger comment only on changed lines

- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
#30 adds `only_report_new_offenses` options, but it might mistake line number (less 1 line).
For example, I create empty file:
```
line 1
line 2
```
git diff says:
```diff
diff --git a/SAMPLE b/SAMPLE
new file mode 100644
index 0000000..7bba8c8
--- /dev/null
+++ b/SAMPLE
@@ -0,0 +1,2 @@
+line 1
+line 2
```
`+1,2` means first line and second line are changed.
But current implementation says `[2, 3]` lines changed (`DangerRubocop#added_lines`).
> Fix added_lines method returns 1 more line number

- .circleci/config.yml
- circle.yml
[CircleCI 1.0 ended at March 15, 2019](https://circleci.com/sunset1-0/).
We need to use CircleCI 2.0 now.
- https://circleci.com/docs/2.0/language-ruby/
- My sample https://circleci.com/gh/mtgto/danger-rubocop/4
> Support CircleCI 2.0

- README.md
- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
When `include_cop_names` is set to something truthy, `#lint` prepends cop names to the output messages.
Example: "Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end."
> Add include_cop_names config var

- danger-rubocop.gemspec
With the addition of `--only-recognized-file-types` flag, the plugin
broke backwards compatibility with older versions of rubocop. For
example, running on 0.82.0 now fails with
```
invalid option: --only-recognized-file-types
```
This adds a minimum version requirement in the gemspec so we can release
a new version with the proper compatibility.
Related: https://github.com/ashfurrow/danger-rubocop/pull/39
> Add minimum rubocop requirement

- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
`danger-rubocop` fails to check new files that only have a single line and instead results in `NoMethodError:  undefined method 'captures' for nil:NilClass`
This is due the the git diff not matching the original regex.
Account for diff hunk identifiers that have the format `@@ -\d,\d +\d @@`
> Handle new files that have a single line

- README.md
Document the following cases:
* `files` option not specified (lint only changed files)
* `files` option is empty string (lint all files)
See #43.
> Improve documentation of `files` option

- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
An error occurs when executing danger-rubocop with a pull request to delete a file only.
The `git.diff_for_file(path)` executed in the added_lines method appears to return nil if no file is added and changed.
So, Added a nil check for that pattern to prevent the error from occurring.
ref: https://github.com/danger/danger/blob/973bd6cdaf43bb08bab78cc1c98dd1e9ecc1a82b/lib/danger/danger_core/plugins/dangerfile_git_plugin.rb#L130-L132
> Fixed a bug that an error occurs when only deleted files are used

- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
We recently moved to [Standard](https://github.com/testdouble/standard/) and I wanted to replicate the experience we had with danger-rubocop. I was about to fork this gem and make a danger-standard but then realised, why not just adapt this one to call `standardrb`? 
`standardrb` is a wrapper around rubocop so I've added a "rubocop_cmd" option to allow us to pass the executable. It defaults to `rubocop` but the user can pass in something else like `standardrb`
Another option would be to make this less generic and just have something like a flag `standard: true`. 
Let me know what you think
> Support standardrb

- README.md
I've added details about the `rubocop_cmd` value and how to use it to support [standard](https://github.com/testdouble/standard/).
I also added a mention of Standard to the top of the README so anyone coming across this repo can quickly see that also supports Standard
> Updated README with details about standardrb

- lib/danger_plugin.rb
This is a fix for an issue reported at https://github.com/ashfurrow/danger-rubocop/issues/55.
With ruby3 support, the interface between Danger's `warn` and `fail` methods has changed.
ref: https://github.com/danger/danger/pull/1286
This PR follows Danger's changes so that no error occurs when danger-rubocop is executed in the Ruby3 environment.
> Delegate keyword arguments for Ruby 3.0

- README.md
- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
The `fail_on_inline_comment` options either always fails or always warns. Rubocop returns a severity level with each offense. Instead of always failing or always warning, there should be an option to fail or warn depending on Rubocop's severity.
> report severity of error based on Rubocop

- lib/danger_plugin.rb
- spec/danger_plugin_spec.rb
Honor config option `include_cop_names` when used together with `report_failure`.
-  Extract the offense message string generation to a new private method
- Support `include_cop_names` when reporting to Danger
- Fix nesting in spec file, specs were all nested within test for inline comments
- Add missing test for when including cop names together with inline comments
> Include cop names in Danger failures
